[package]
name = "pmm_extractor"
version = "0.1.0"
authors = ["zhouhang95 <765229842@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding="*"
byteorder="*"
